# Generated by Django 3.1.5 on 2021-01-30 14:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Magazine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Magazine Issue Name')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('tag_line', models.CharField(help_text='Magazine issue tag line', max_length=190, verbose_name='Tag line')),
                ('cover_image', models.ImageField(upload_to='uploads/', verbose_name='Cover Image')),
                ('description', models.TextField(help_text='describe main issues covered', verbose_name='Magazine Issue Description')),
                ('date', models.DateField()),
            ],
            options={
                'verbose_name': 'Magazine Issue',
                'verbose_name_plural': 'Magazine Issue',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Tag Name')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(help_text='describe the tag/category', verbose_name='Tag Description')),
                ('image', models.ImageField(upload_to='uploads/', verbose_name='Tag Image')),
            ],
            options={
                'verbose_name': 'Tags',
                'verbose_name_plural': 'Tags',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='News Title')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('image', models.ImageField(upload_to='static/uploads/', verbose_name='Image')),
                ('body', models.TextField(verbose_name='News Body')),
                ('date', models.DateField()),
                ('Tag', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='app.tag')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'News Updates',
                'verbose_name_plural': 'News Updates',
            },
        ),
        migrations.CreateModel(
            name='ImageGallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='uploads/')),
                ('name', models.CharField(max_length=20, verbose_name='Image Name')),
                ('caption', models.CharField(max_length=10, verbose_name='Image Caption')),
                ('description', models.TextField(verbose_name='Description')),
                ('Tag', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.tag')),
            ],
            options={
                'verbose_name': 'Image Gallery',
                'verbose_name_plural': 'Image Gallery',
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='Article Title')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('date', models.DateField()),
                ('image', models.ImageField(upload_to='uploads/', verbose_name='Cover Image')),
                ('article_feature', models.CharField(choices=[('main', 'Main'), ('featured', 'Featured')], max_length=20, verbose_name='Tag')),
                ('body', models.TextField(verbose_name='Article Body')),
                ('subheading1', models.CharField(blank=True, max_length=100, null=True, verbose_name='Sub Heading (optional)')),
                ('body1', models.TextField(blank=True, null=True, verbose_name='Article Body (optional)')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('magazine', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.magazine')),
                ('tag', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='app.tag')),
            ],
            options={
                'verbose_name': 'Articles',
                'verbose_name_plural': 'Articles',
            },
        ),
    ]
