# Generated by Django 3.1.5 on 2021-01-30 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='magazine',
            name='issue_date',
            field=models.CharField(default='Jan - March 2021', help_text='Example: July - May 2020', max_length=100, unique=True, verbose_name='Issue Date'),
        ),
    ]
