# Generated by Django 3.1.5 on 2021-01-31 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_magazine_issue_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_feature',
            field=models.CharField(choices=[('main', 'Main'), ('featured', 'Featured')], max_length=20, verbose_name='Article Feature'),
        ),
    ]
