# Generated by Django 3.1.5 on 2021-02-12 20:00

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_tag_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='description',
            field=ckeditor.fields.RichTextField(default='Tag description', verbose_name='Tag Description'),
        ),
    ]
