# Generated by Django 3.1.5 on 2021-01-31 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210131_0802'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='Description',
            field=models.TextField(default='brief description', max_length=300, verbose_name='Article Description'),
        ),
    ]
