# Generated by Django 3.1.5 on 2021-01-31 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_article_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='Description',
            field=models.TextField(default='brief description', max_length=300, verbose_name='Article Description'),
        ),
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(upload_to='', verbose_name='Cover Image'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='image',
            field=models.ImageField(upload_to='', verbose_name='Tag Image'),
        ),
    ]
