# Generated by Django 3.1.5 on 2021-02-13 07:06

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0005_magazine'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='News Title')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('image', models.ImageField(upload_to='images/', verbose_name='News Cover Image')),
                ('description', ckeditor.fields.RichTextField(verbose_name='Article Description')),
                ('body', ckeditor.fields.RichTextField(verbose_name='News Body')),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', help_text='Published or Draft', max_length=20, verbose_name='News Status')),
                ('news_feature', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], help_text='News to be featured on home page', max_length=20, verbose_name='Article Feature')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tag', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='app.tag')),
            ],
            options={
                'verbose_name': 'News Updates',
                'verbose_name_plural': 'News Updates',
            },
        ),
    ]
