# Generated by Django 3.1.5 on 2021-02-13 07:33

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0006_news'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='Article Title')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('date', models.DateField()),
                ('image', models.ImageField(upload_to='', verbose_name='Cover Image')),
                ('article_feature', models.CharField(choices=[('main', 'Main'), ('featured', 'Featured')], max_length=20, verbose_name='Article Feature')),
                ('article_status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=20, verbose_name='Article Status')),
                ('body', ckeditor.fields.RichTextField(verbose_name='Article Body')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('magazine', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.magazine')),
                ('tag', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='app.tag')),
            ],
            options={
                'verbose_name': 'Articles',
                'verbose_name_plural': 'Articles',
            },
        ),
    ]
