# Generated by Django 3.1.5 on 2021-02-06 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20210131_0938'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=20, verbose_name='Article Status'),
        ),
    ]
