# Generated by Django 3.1.5 on 2021-02-06 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_article_article_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='article_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=20, verbose_name='News Status'),
        ),
    ]
