const tenants = [
  {
    id: 1,
    name: 'Leanne Graham',
    username: 'Bret',
    email: 'Sincere@april.biz',
    phone: '1-770-736-8031 x56442',
    house: 'Waiyaki 1',
    unit: 'WA001',
    accounts: {
      balance: 0,
      arrears: 39000,
      total_paid: 90039,
    },
  },
  {
    id: 2,
    name: 'Ervin Howell',
    username: 'Antonette',
    email: 'Shanna@melissa.tv',
    phone: '010-692-6593 x09125',
    house: 'Waiyaki 2',
    unit: 'WA301',
    accounts: {
      balance: 324,
      arrears: 0,
      total_paid: 20000,
    },
  },
  {
    id: 3,
    name: 'Clementine Bauch',
    username: 'Samantha',
    email: 'Nathan@yesenia.net',
    phone: '1-463-123-4447',
    house: 'Waiyaki 1',
    unit: 'WA001',
    accounts: {
      balance: 10250,
      arrears: 3400,
      total_paid: 19023,
    },
  },
  {
    id: 4,
    name: 'Patricia Letotal_paidack',
    username: 'Karianne',
    email: 'Julianne.OConner@kory.org',
    phone: '493-170-9623 x156',
    house: 'Waiyaki 1',
    unit: 'WA001',
    accounts: {
      balance: 23,
      arrears: 0,
      total_paid: 88000,
    },
  },
  {
    id: 5,
    name: 'Chelsey Dietrich',
    username: 'Kamren',
    email: 'Lucio_Hettinger@annie.ca',
    phone: '(254)954-1289',
    house: 'Waiyaki 1',
    unit: 'WA001',
    accounts: {
      balance: 324,
      arrears: 0,
      total_paid: 20000,
    },
  },
  {
    id: 6,
    name: 'Mrs. Dennis Schulist',
    username: 'Leopoldo_Corkery',
    email: 'Karley_Dach@jasper.info',
    phone: '1-477-935-8478 x6430',
    house: 'Waiyaki 1',
    unit: 'WA001',
    accounts: {
      balance: 324,
      arrears: 0,
      total_paid: 20000,
    },
  },
  {
    id: 9,
    name: 'Glenna Reichert',
    username: 'Delphine',
    email: 'Chaim_McDermott@dana.io',
    phone: '(775)976-6794 x41206',
    house: 'Waiyaki 1',
    unit: 'WA001',
    accounts: {
      balance: 0,
      arrears: 0,
      total_paid: 0,
    },
  },
  {
    id: 10,
    name: 'Clementina DuBuque',
    username: 'Moriah.Stanton',
    email: 'Rey.Padberg@karina.biz',
    phone: '024-648-3804',
    house: 'Waiyaki 1',
    unit: 'WA001',
    accounts: {
      balance: 5400,
      arrears: 3900,
      total_paid: 22000,
    },
  },
]

export default tenants
